### ISSUE TITLE
Add support for U256 and I256 types

### ISSUE THREAD

**Issue by Robbepop** [paritytech/canvas-ui#10]
Currently the UI can handle all primitive types such as Rust's `i32`, `u64`, `bool`, arrays, tuples and compound types.
However, for Solang we need support for Ethereum's `U256` and `I256` types.

What is the preferred concrete types to implement for this? https://github.com/seanyoung
@seanyoung

**Comment by kwingram25** [comment]
Closed with newest @polkadot/api versions
