### ISSUE TITLE
`flipper` cannot be deployed with `default()` constructor

### ISSUE THREAD

**Issue by cmichi** [paritytech/canvas-ui#102]
Heres's the contract: [flipper.contract.zip](https://github.com/paritytech/canvas-ui/files/6477362/flipper.contract.zip).

The `Instantiate` button is greyed out/inactive and the console has this error:

```
main.13db4e81.js:291 Expected 0 arguments to contract message 'default', found 1
```

I suspect that an issue is that `flipper`'s `new(initial_value: bool)` constructor is selected by default. If one then selects the `default()` constructor that `initial_value` argument is maybe still required, even though it shouldn't be?

It works with the polkadot-js UI.

**Comment by kwingram25** [comment]
Closed by #104
