### ISSUE TITLE
Unable to upload ink!'s `trait-erc20` example

### ISSUE THREAD

**Issue by cmichi** [paritytech/canvas-ui#105]
When trying to upload [the `trait-erc20` example](https://github.com/paritytech/ink/tree/master/examples/trait-erc20) to the latest `canvas-node` chain I get this error on the web dev console:
```
main.e7e20b2c.js:291 K.tx[n] is not a function
```
The "Instantiate" button is greyed out and I can't upload the contract file.

Here's the compiled contract: [trait_erc20.contract.zip](https://github.com/paritytech/canvas-ui/files/6568243/trait_erc20.contract.zip).

It works in the polkadot-js UI.

**Comment by kwingram25** [comment]
Fixed
