### ISSUE TITLE
Add support for displayName

### ISSUE THREAD

**Issue by Robbepop** [paritytech/canvas-ui#11]
It seems that the UI sometimes does not properly display the `displayName` of function parameters and function return types and instead displays their technical names which is often not preferred. The distinction between the name of the type in question and its `displayName` when used as parameter or return type becomes immediately clear when we are talking about type aliases.

Whereas the type's name always resolved aliases and always refers to the real underlying type the `displayName` does not and instead refers to the actual name that is used on the exact function argument or return type.

## Example

```rust
type Balance = u64;

#[ink(message)]
pub fn transfer(&mut self, to: AccountId, amount: Balance) { ... }
```

In this example the `amount`function argument has a `displayName` of `Balance` whereas it has a type name of `u64`.
Ideally the UI could display both if they are different so that a user knows the type's name on the use site as well as its underlying real name or identifier.

## Screenshot

The screenshot shows how `Balance` is shown for `total_supply` but not for `new`. Instead the `new` constructor shows `u128` instad of `Balance`.

![2020-10-21-131022_913x348_scrot](https://user-images.githubusercontent.com/8193155/96712076-d426b880-139e-11eb-92e0-bf51b8408875.png)

**Comment by kwingram25** [comment]
This appears to be resolved -

![Screenshot from 2020-11-15 22-05-59](https://user-images.githubusercontent.com/879755/99218243-cfcba080-278e-11eb-9832-5104fc901c7f.png)
