### ISSUE TITLE
Update for metadata v14

### ISSUE THREAD

**Issue by nuke-web3** [paritytech/canvas-ui#113]
The `cargo-contracts 0.15 ` release is reported by @justin-parity  to not work with the following:

![image](https://user-images.githubusercontent.com/35669742/138024383-adff80f7-1c6d-4cc5-8ce7-1795beee3ad7.png)

**Comment by NukeManDan** [comment]
For reference, the Devhub FE template needed this: https://github.com/substrate-developer-hub/substrate-front-end-template/commit/daf38f1417ef830172e6367a88bc0766cc71d576
