### ISSUE TITLE
Support markdown in shown documentation

### ISSUE THREAD

**Issue by Robbepop** [paritytech/canvas-ui#20]
The Canvas UI can show the documentation of ink! messages, constructors, events etc.
However, this documentation is currently completely unformatted although being preformatted (through means of Rust docs) by Rust's markdown flavor.
It would be a nice feature to show the documentation of those entities with proper markdown formatting.

Also it should be possible to collapse documentation of the items, which will be useful for especially big contracts.
Collapsing the docs will only show the first line of the documentation (or none).

**Comment by erler** [comment]
Played around with some ideas. The accordion solution might not work as the metadata can be quite long in some cases:

<img width="556" alt="canvas-ui_abi_accordion" src="https://user-images.githubusercontent.com/7072141/98651376-769ce080-233a-11eb-8edf-c976f0726422.png">

@kwingram25 and me had the idea of using a modal instead. Initially, I had everything in one modal, but again it was getting quite long, so it probably makes more sense to have one modal per message, constructor etc.

<img width="1440" alt="canvas-ui_abi_modal_short" src="https://user-images.githubusercontent.com/7072141/98652138-7b15c900-233b-11eb-92f6-4861302ba5de.png">

There was also the idea of giving a preview when hovering a message, event etc. - but this could also be a normal tooltip instead, just to give the user an indication that there's documentation.

<img width="1440" alt="canvas-ui_abi_popup" src="https://user-images.githubusercontent.com/7072141/98652313-bfa16480-233b-11eb-82ca-5f3130bdba44.png">

**Comment by Robbepop** [comment]
I dislike modal dialogs in general tbh. I like the idea of the on-hover tooltip very much and also think it would be nice if the docs of the first line was shown and for the rest the user had to click to "enlarge" docs per message or constructor if possible. In the Rust ecosystem your docs by-convention start with a single summary line and followed by potential wall-of-text that should be hidden by default.

**Comment by kwingram25** [comment]
I agree on tooltip, think it will be a better experience than modal

**Comment by erler** [comment]
Cool, let's go for a tooltip / popup then. Will make some specs in Figma.
