### ISSUE TITLE
Solidity events are not showing

### ISSUE THREAD

**Issue by seanyoung** [paritytech/canvas-ui#24]
Steps to reproduce:
 -  Deploy
[incrementer.zip](https://github.com/paritytech/canvas-ui/files/5506185/incrementer.zip)
 - Execute the get function or the inc function (rpc or transaction)
 - Results: no event visible

Expected results:
 - Both the transaction and the rpc call should show that the event `incrementer.Foo` was emitted and the value

**Comment by seanyoung** [comment]
dup #18

**Comment by Robbepop** [comment]
Can we close this duplicate?

**Comment by seanyoung** [comment]
Yes, I should not have raised it. 
Duplicate of #18
