### ISSUE TITLE
frontend raise i.toJSON is not a function error

### ISSUE THREAD

**Issue by ww8912188** [paritytech/canvas-ui#30]
Hi guys,

I searched all over with no luck. Hope someone could shine some light on below issue.

I tried to deploy contract https://github.com/ww8912188/ink-contracts/tree/main/voting on https://paritytech.github.io/canvas-ui/#/upload.

It works smoothly for the upload process but deploy, it raise below error:

![image](https://user-images.githubusercontent.com/17057416/99874485-4e0ec380-2c23-11eb-9fb1-694c70ef5d25.png)

Can someone take a look at this issue? This contract works last week to my memory. 
I also tried to install canvas-ui on locally with the newest release version v0.44.1. But it seems the UI looks totally different 
from the one of https://paritytech.github.io/canvas-ui/#/upload, so I cannot debug my code.

Regards,
Nan

**Comment by ww8912188** [comment]
I tried to deploy it on https://polkadot.js.org/apps/#/contracts, and it seems it works smoothly.

**Comment by kwingram25** [comment]
Please try again, I believe this should be fixed now after new PR

**Comment by ww8912188** [comment]
I've tried it and it works smoothly now. Thanks kwingram25, really appreciate. Wish canvas-ui better and better. Close this issue.
