### ISSUE TITLE
Docs not shown for contract calls

### ISSUE THREAD

**Issue by cmichi** [paritytech/canvas-ui#38]
I think the `docs` disappeared with the migration to the `.contract` file:

Before:
![before](https://user-images.githubusercontent.com/241530/101819062-0a71f000-3b25-11eb-87f3-13457428f11b.png)

Currently:
![bug](https://user-images.githubusercontent.com/241530/101819099-1493ee80-3b25-11eb-9974-959010a82769.png)

**Comment by kwingram25** [comment]
It should appear on mouseover in an expanded tooltip now.
