### ISSUE TITLE
Type mismach issue. Put code extrinsic fails in `v2.0.0`

### ISSUE THREAD

**Issue by riusricardo** [paritytech/canvas-ui#6]
![image](https://user-images.githubusercontent.com/9488369/95740519-f7f64a00-0c8c-11eb-9dcb-11183082ace9.png)
Canvas commit: `0516adfe4b17549b837080b6d49dd2472af5706f`
Substrate commit: `a200cdb93c6af5763b9c7bf313fa708764ac88ca`

**Comment by Robbepop** [comment]
Try compiling your ink! smart contract and metadata using the most recent nightly.
The UI works perfectly fine for me.

**Comment by riusricardo** [comment]
@Robbepop doesn't work.
I'm using: 
Cargo contract: `169c65b4a61d00cb92fa393d0def6851f392d3e2`
Canvas commit: `0516adfe4b17549b837080b6d49dd2472af5706f`
Substrate commit: `a200cdb93c6af5763b9c7bf313fa708764ac88ca`

**Comment by riusricardo** [comment]
This error is usually related to polkadot js types. It cant encode/decode the extrinsic.

**Comment by Robbepop** [comment]
Try our `canvas-node` implementation at `master`:
https://github.com/paritytech/canvas-node

**Comment by riusricardo** [comment]
I am closing this issue as it works with canvas-node.
