### ISSUE TITLE
Attribute Polkadot JS Apps in license headers

### ISSUE THREAD

**Issue by Robbepop** [paritytech/canvas-ui#61]
Currently Canvas UI does not properly give attribution to things that it copied from Polkadot JS Apps or was inspired from.

If Canvas UI authors copy'n'pasted a file from Polkadot JS Apps the license header will be the original:
```rust
// Copyright 2017-2021 @polkadot/apps-* authors & contributors
// SPDX-License-Identifier: Apache-2.0
```

If Canvas UI authors modified a file that has been copied from Polkadot JS Apps it will in the future have a license header like this instead:
```rust
// Copyright 2017-2021 @polkadot/apps-* authors & contributors
// and @canvas-ui/app-* authors & contributors
// SPDX-License-Identifier: Apache-2.0
```

**Comment by kwingram25** [comment]
Closed in #62
