### ISSUE TITLE
Uploading contract fails with `canvas-node` master

### ISSUE THREAD

**Issue by cmichi** [paritytech/canvas-ui#77]
I'm unable to upload `flipper` with the current `canvas-node` master. This is the error I get:

```
contracts.instantiateWithCode
1002: Verification Error: Runtime error:
Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: None, desc: "Could not decode `MultiAddress`, variant doesn\'t exist" } }): RuntimeApi, Execution failed: ApiError, FailedToConvertParameter { function: \"validate_transaction\", parameter: \"tx\", error: Error { cause: None, desc: \"Could not decode `MultiAddress`, variant doesn\\\'t exist\" } }
```

**Comment by poetrysystems** [comment]
+1. Is a blocking issue for development.

**Comment by ILoomans** [comment]
I am also getting this error when I am running my substrate-node-template configured with the contracts pallet, and when running the canvas-node after having cloned the repository and  running the node. 

Interestingly when i run  node through through the canvas command eg: "canvas --dev --tmp" , I am able to upload and instantiate the contract fine.  Hope this is resolved soon!

**Comment by trace-andreason** [comment]
@poetrysystems @ILoomans here is a temporary workaround until fixed in a better way. You'll have to be running locally, but just replace this line https://github.com/paritytech/canvas-ui/blob/master/packages/react-api/src/Api.tsx#L173 with the below:
```
    api = new ApiPromise({ provider, registry, signer, typesChain, typesSpec,
    types: {
    "Address": "AccountId"
    }});
```
I looked into fixing this, but the type stuff going on in this project is a bit advanced as it can handle multiple chains...

relevant docs: https://polkadot.js.org/docs/api/start/types.extend

**Comment by patrickodacre** [comment]
@trace-andreason Thanks for posting a work around, but I'm afraid it isn't working in my case. I'm getting the following when attempting to instantiate a new contract on the node template after following the tutorial here - https://substrate.dev/docs/en/tutorials/add-contracts-pallet/:

```
1002: Verification Error: Runtime error: Execution failed: ApiError("Could not convert parameter `tx` between node and runtime: Could not decode `MultiAddress`, variant doesn\'t exist"): RuntimeApi, Execution failed: ApiError, \"Could not convert parameter `tx` between node and runtime: Could not decode `MultiAddress`, variant doesn\\\'t exist\
```
Canvas node works just fine; I'm only seeing this error on a fresh node template after following that tutorial.

Thanks

**Comment by ILoomans** [comment]
@patrickodacre 
I think this should do the trick!
```
const types =  {"Address": "MultiAddress", "LookupSource": "MultiAddress"}
const wsProvider = new WsProvider('ws://127.0.0.1:9944')
const api = await ApiPromise.create({ provider: wsProvider, types })
```

**Comment by patrickodacre** [comment]
@ILoomans Thanks!

Altering the snippet [above](https://github.com/paritytech/canvas-ui/issues/77#issuecomment-813102520) with your suggestion worked:

Replacing [this line](https://github.com/paritytech/canvas-ui/blob/master/packages/react-api/src/Api.tsx#L173) with the following did the trick:

```
  api = new ApiPromise({ provider, registry, signer, typesChain, typesSpec,
    types: {
    "Address": "MultiAddress"
    }});
```

And I can confirm I was able to instantiate and execute a test contract.

**Comment by cmichi** [comment]
I'm closing the issue as I don't get the issue anymore, my understanding is that it has been fixed everywhere by now.
