### ISSUE TITLE
Verification Error: Execution(ApiError("Could not convert parameter tx ...

### ISSUE THREAD

**Issue by leeduckgo** [paritytech/canvas-ui#80]
![image](https://user-images.githubusercontent.com/12784118/112933993-71a6c500-9153-11eb-9dcf-f8cbb09653f6.png)
Problem when I using canvas local dev node to deploy ink! contract

**Comment by trace-andreason** [comment]
@leeduckgo see issue #77, I posted a temporary work around

**Comment by leeduckgo** [comment]
> @leeduckgo see issue #77, I posted a temporary work around

thx a lot

**Comment by statictype** [comment]
@leeduckgo updating canvas-node should fix that. there is no upload step anymore. 
`cargo install canvas-node --git https://github.com/paritytech/canvas-node.git --tag v0.1.5 --force --locked`

**Comment by cmichi** [comment]
I'm closing the issue as I also don't get the issue anymore, please re-open if you still have issues.
