### ISSUE TITLE
Returning a value wrapped in option from a message results in error

### ISSUE THREAD

**Issue by JayPavlina** [paritytech/canvas-ui#84]
Returning a value wrapped in an option results in the following error:

`Uncaught error. Something went wrong with the query and rendering of this component. createType(Option):: Cannot construct unknown type Option`

If the value is None, there is no error. It only happens when it is Some.

To reproduce, run the [ink erc721 example](https://github.com/paritytech/ink/tree/master/examples/erc721). Call mint on a token ID. Then call owner_of on the same token ID you just minted.

**Comment by cmichi** [comment]
I just ran into this as well with the most recent version of the `canvas-ui`. So the bug still exists.

**Comment by cmichi** [comment]
Closed via https://github.com/paritytech/canvas-ui/pull/106.
