### ISSUE TITLE
Add support for enum types

### ISSUE THREAD

**Issue by Robbepop** [paritytech/canvas-ui#9]
Currently the UI only supports primitives as well as compound types (tuples and structs).
However, it is missing support for `enum` types that are any variant of a given fixed list of compound of enum type.
Ideally the UI supports both input and output of those types.

- [ ] Implement UI to allow inputting `enum` types into contracts.
- [ ] Implement UI to properly display return values of `enum` types.

**Comment by kwingram25** [comment]
Are there any sample contracts to test enum types with?

**Comment by Robbepop** [comment]
Nope.

There are the following types of supported enums:

# C-like Enums

```rust
enum Weekday {
    Monday,
    Tuesday,
    Wednesday,
    Thursday,
    Friday,
    Saturday,
    Sunday,
}
```

## Enum with Data

```rust
enum IntOrFloat {
    Integer(i32),
    Float(f32),
}
```

or the same with names:

```rust
enum IntOrFloat {
    Integer { value: i32 },
    Float { value: f32 },
}
```

# Enum with pure variants and data variants

```rust
enum Color {
    Red, Blue, Green, Yellow,
    Rgb { r: u8, g: u8, b: u8 },
    Rgba { r: u8, g: u8, b: u8, a: u8 },
}
```

# Enum in Enums

```rust
enum Tree {
    Leaf { value: i32 },
    Node { right: Box<Tree>, left: Box<Tree> },
}
```

You can write an ink! contract (or if you want, we can provide one for you) with all those enums contained in ink! messages  or constructors inputs and outputs.

**Comment by Robbepop** [comment]
ink! source code for a contract using the above enums can be found here:
https://gist.github.com/Robbepop/c977b344fd126ea599f7677cf28143b5

Due to a bug it is currently missing the `Tree` enum.

**Comment by kwingram25** [comment]
Determined to be an underlying problem with api-contract - fixing

**Comment by Robbepop** [comment]
> Due to a bug it is currently missing the Tree enum.

This is due to an ink! bug. Sorry for confusion!

**Comment by kwingram25** [comment]
Addressed api problems but still a lot to figure out for rendering enum values, i.e. on the sign and submit pages

**Comment by Robbepop** [comment]
Please also consider the following recursively defined enum:
```rust
pub enum Tree {
    Leaf { value: i32 },
    Node { lhs: Box<Tree>, rhs: Box<Tree> },
}
```

**Comment by Robbepop** [comment]
I did not yet include it into our example contract because `scale-info` currently has a bug serializing it.
